# Generated by Django 3.0.7 on 2024-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210627_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='men_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='women_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/additional/'),
        ),
        migrations.AddField(
            model_name='product',
            name='carats_total_weight',
            field=models.CharField(choices=[('1/2 Ct.t.w.', '1/2 Ct.t.w.'), ('1 Ct.t.w.', '1 Ct.t.w.'), ('1.5 Ct.t.w.', '1.5 Ct.t.w.'), ('2 Ct.t.w.', '2 Ct.t.w.')], default='1/2 Ct.t.w.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gram_weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight of the jewelry piece in grams (approximately)', max_digits=6, verbose_name='Gram Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Length of the jewelry piece in millimeters', max_digits=5, verbose_name='Length (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(choices=[('10kt White Gold', '10kt White Gold'), ('14kt Yellow Gold', '14kt Yellow Gold'), ('18kt Rose Gold', '18kt Rose Gold'), ('Platinum', 'Platinum')], default='10kt White Gold', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_gem_color_clarity',
            field=models.CharField(default='G-H / I3', help_text='Format: Color/Clarity (e.g., G-H / I3)', max_length=50, verbose_name='Primary Gem Color / Clarity'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_gem_shape',
            field=models.CharField(choices=[('Round', 'Round'), ('Princess', 'Princess'), ('Emerald', 'Emerald'), ('Oval', 'Oval'), ('Marquise', 'Marquise'), ('Cushion', 'Cushion'), ('Pear', 'Pear'), ('Heart', 'Heart')], default='Round', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_gem_type',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('Sapphire', 'Sapphire'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald')], default='Diamond', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('Crosses', 'Crosses'), ('Rings', 'Rings'), ('Earrings', 'Earrings'), ('Bracelets', 'Bracelets'), ('Necklaces', 'Necklaces'), ('Pendants', 'Pendants')], default='Crosses', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Width of the jewelry piece in millimeters', max_digits=5, verbose_name='Width (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('None', 'None'), ('Men', 'Men'), ('Women', 'Women')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Color', 'Color'), ('Color-Size', 'Color-Size')], default='None', max_length=20),
        ),
    ]
